# If you publish your app to the Microsoft Store,
# the installation package will be signed automatically by the store.
display_name: PicGuard
logo_path: logo\logo-512.png
languages: en-us, zh-cn
architecture: x64
capabilities: "internetClient,picturesLibrary"
install_certificate: "false"
store: "false"

# msix_version: 1.0.0.0 # If not set, the value of `version` is used
# With Your Own Certificate
certificate_path: CERTIFICATE_PATH_PLACEHOLDER
certificate_password: CERTIFICATE_PASSWORD_PLACEHOLDER

# For Publish To Windows Store
identity_name: IDENTITY_NAME_PLACEHOLDER
publisher: PUBLISHER_PLACEHOLDER
publisher_display_name: PUBLISHER_NAME_PLACEHOLDER
