# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      sentry-dependencies:
        patterns: [ "sentry_flutter", "sentry_logging" ]
      slang-dependencies:
        patterns: [ "slang_flutter", "slang_build_runner" ]

#  - package-ecosystem: "cargo" # See documentation for possible values
#    directory: "/rust" # Location of package manifests
#    schedule:
#      interval: "daily"
