targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          output_directory: lib/i18n
          output_file_name: i18n.g.dart
          maps:
            - locales
          contexts:
            Flavor:
              default_parameter: flavor # by default: "context"
