targets:
  $default:
    builders:
      flutter_gen_runner: # or flutter_gen
        options:
          output: lib/generated/ # Optional (default: lib/gen/)
          line_length: 80 # Optional (default: 80)

          colors:
            enabled: true
            outputs:
              class_name: PGColors
            inputs:
              - assets/color/colors.xml

      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          output_directory: lib/i18n
          output_file_name: i18n.g.dart
          timestamp: false
          maps:
            - locales
          contexts:
            Flavor:
              default_parameter: flavor # by default: "context"
