display_name: PicGuard
package_name: picguard
maintainer:
  name: kjxbyz
  email: hello@kjxbyz.com
priority: optional
section: x11
installed_size: 12000
essential: false
icon: logo/logo-512.png
metainfo: linux/shared/picguard.metainfo.xml

keywords:
  - PicGuard
  - Watermark
  - Assistant
  - Watermark Assistant

generic_name: PicGuard

categories:
  - Utility

startup_notify: true
