display_name: PicGuard
package_name: picguard
maintainer:
  name: kjxbyz
  email: support@picguard.app
priority: optional
section: x11
installed_size: 12000
essential: false
icon: logo/logo-512.png
metainfo: linux/shared/picguard.metainfo.xml

keywords:
  - PicGuard
  - Watermark
  - Assistant
  - Watermark Assistant

generic_name: PicGuard

categories:
  - Utility

# direct dependencies required by the application
# refer: https://www.debian.org/doc/debian-policy/ch-relationships.html
# https://www.debian.org/distrib/packages#search_packages
dependencies:
  - libc6 (>= 2.35)
  - libayatana-appindicator3-1

startup_notify: true
