name: picguard
version: 2.0.1.442
summary: Your pictures, your signature.
description: |
  Introducing **PicGuard** - the ultimate solution for securing and customizing your digital photos. With our app, you can easily add watermarks to your images to protect your creative work and maintain your privacy.

  **PicGuard** offers robust privacy protection features, ensuring your personal and sensitive information remains safeguarded. It's highly customizable, allowing you to personalize watermarks with various fonts, styles, and designs to suit your needs.

  Accessible on web, mobile, and desktop, you can seamlessly integrate and manage your watermarking tasks across all your devices. **PicGuard**, as an open-source tool, it's not only free but also continuously improved by a community of developers dedicated to providing the best user experience.

  Download **PicGuard** today and take control of your photo security and personalization like never before!
icon: snap/gui/picguard.png
title: PicGuard
contact: hello@kjxbyz.com
license: GPL-3.0-only
source-code: https://github.com/picguard/picguard
issues: https://github.com/picguard/picguard/issues
website: https://www.picguard.app
confinement: strict
base: core24
grade: stable
slots:
  dbus-picguard: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.kjxbyz.PicGuard # adjust accordingly to your app name and
apps:
  picguard:
    command: picguard
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
      - home
    slots:
      - dbus-picguard
parts:
  picguard:
    source: .
    plugin: flutter
    # flutter-target: lib/main.dart # The main entry-point file of the application
    build-packages:
      - curl
      - libcurl4-openssl-dev
      - git
      - unzip
      - xz-utils
      - zip
      - libglu1-mesa
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libstdc++-12-dev
      - libayatana-appindicator3-dev
    build-environment:
      - FLUTTER_REPO: https://github.com/flutter/flutter.git
      - FLUTTER_VERSION: 3.29.2
      - FLUTTER_TARGET: lib/main_free.dart
    override-build: |
      # https://github.com/canonical/snapcraft/blob/main/snapcraft/parts/plugins/flutter_plugin.py
      PG_FLUTTER_BUILD_DIR="$CRAFT_PART_BUILD/flutter-distro"
      if [ -d "$PG_FLUTTER_BUILD_DIR" ]; then
        echo "$PG_FLUTTER_BUILD_DIR"
        rm -rf $PG_FLUTTER_BUILD_DIR
      fi
      git clone --depth 1 -b $FLUTTER_VERSION $FLUTTER_REPO $PG_FLUTTER_BUILD_DIR
      
      # https://github.com/canonical/snapcraft/pull/5264
      # Fixed in 3.29.1
      # rm -f "$PG_FLUTTER_BUILD_DIR/engine/src/.gn"
      flutter doctor -v
      flutter precache --linux
      flutter pub get
      flutter build linux --release --dart-define-from-file=.env --target $FLUTTER_TARGET
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
