name: Test Linux rpm (free)

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  rpm:
    name: Create linux rpm
    runs-on: ubuntu-22.04
    container:
      image: fedora:40
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "17.x"
          distribution: 'temurin'

      - name: Install dependencies for Linux
        run: |
          sudo dnf update -y && sudo dnf upgrade -y
          sudo dnf install -y curl which git unzip xz zip mesa-libGLU
          sudo dnf install -y clang cmake ninja-build pkgconf-pkg-config gtk3-devel xz-devel libstdc++-devel
          sudo dnf install -y rpm-build patchelf

      - name: Install libayatana-appindicator-gtk3
        run: |
          # used by tray_manager
          sudo dnf install -y libayatana-appindicator-gtk3

      - name: Install jq
        run: sudo dnf install -y jq

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.5'

      - name: Fix git safe directory issue
        run: git config --global --add safe.directory "$FLUTTER_ROOT"

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Configure .env
        run: echo "$ENV_KEY" | base64 --decode > .env
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64 }}

      - name: Install fastforge
        run: dart pub global activate fastforge

      - name: Update make_config.yaml
        run: rm -f "$(pwd)/linux/packaging/rpm/make_config-pro.yaml"

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build RPM
        run: |
          export SENTRY_NATIVE_BACKEND=breakpad
          fastforge package \
            --skip-clean \
            --flutter-build-args "dart-define-from-file=.env,target=lib/main_free.dart" \
            --platform linux \
            --targets rpm \
            --artifact-name '{{name}}-{{build_name}}.{{build_number}}-{{platform}}-amd64.{{ext}}'

      # Package the build.
      - name: Copy build for rpm
        run: ls -laR
        working-directory: dist

      - uses: actions/upload-artifact@v4
        with:
          name: linux-rpm-artifact
          path: ./dist/**/*.rpm

      - name: Clean up
        if: ${{ always() }}
        run: rm -f .env
