name: Test Tools

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  windows-signtool:
    name: Create signtool
    runs-on: windows-2022
    steps:
      - name: Check SignTool
        run: |
          cd 'C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool'
          ls -R

  windows-msvc:
    name: Create msvc
    runs-on: windows-2022
    steps:
      - name: Check msvc
        run: |
          $directories = Get-ChildItem -Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC" -Directory | Where-Object { $_.Name -match '^[0-9]{1,}' }

          # 如果目录列表不为空，则找到最后一个目录
          if ($directories.Count -gt 0) {
              $lastDirectory = $directories[-1]
              Write-Output "最后一个以数字开头的目录是: $($lastDirectory.FullName)"
          } else {
              Write-Output "未找到以数字开头的目录"
          }

#  windows-msix:
#    name: Create msix
#    runs-on: windows-2022
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install certificates
#        run: |
#          echo $env:RUNNER_TEMP
#          $certificate_path = "$env:RUNNER_TEMP\picguard.pfx"
#          # https://stackoverflow.com/questions/15414678/how-to-decode-a-base64-string
#          # https://stackoverflow.com/questions/66239147/pfx-encoded-and-back-to-pfx-in-powershell
#          $bytes = echo $env:WINDOWS_CERTIFICATE | %{[Convert]::FromBase64String($_)}
#          [IO.File]::WriteAllBytes("$certificate_path", $bytes)
#          (get-content windows\packaging\msix\make_config.yaml) -replace 'PUBLISHER_NAME_PLACEHOLDER', $env:WINDOWS_PUBLISHER_NAME -replace 'IDENTITY_NAME_PLACEHOLDER', $env:WINDOWS_IDENTITY_NAME -replace 'CERTIFICATE_PATH_PLACEHOLDER', $certificate_path -replace 'CERTIFICATE_PASSWORD_PLACEHOLDER', $env:WINDOWS_CERTIFICATE_PASSWORD -replace 'PUBLISHER_PLACEHOLDER', $env:WINDOWS_PUBLISHER | Out-File -encoding utf8 windows\packaging\msix\make_config.yaml
#        env:
#          WINDOWS_PUBLISHER_NAME: ${{ secrets.WINDOWS_PUBLISHER_NAME }}
#          WINDOWS_IDENTITY_NAME: ${{ secrets.WINDOWS_IDENTITY_NAME }}
#          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
#          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
#          WINDOWS_PUBLISHER: ${{ secrets.WINDOWS_PUBLISHER }}
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: msix-artifact
#          path: |
#            windows\packaging\msix\make_config.yaml

  windows-yq:
    name: Update config
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        shell: pwsh
        run: |
          choco install yq
          yq --version

      - name: Update config
        shell: pwsh
        run: |
          $SETUP_ICON_FILE = "$pwd\windows\runner\resources\app_icon.ico"
          echo $SETUP_ICON_FILE
          
          $yamlFile = ".\windows\packaging\exe\make_config.yaml"
          $yamlContent = Get-Content -Raw -Path $yamlFile
          
          # 获取环境变量的值
          $appId = (Get-Item -Path Env:WINDOWS_APP_ID).Value
          $publisherName = (Get-Item -Path Env:WINDOWS_PUBLISHER_NAME).Value
          
          # 使用 yq 更新多个字段
          $updatedYamlContent = echo $yamlContent | yq e ".app_id = `"$appId`" | .publisher_name = `"$publisherName`" | .setup_icon_file = `"$SETUP_ICON_FILE`"" -
          
          # 将更新后的内容写回文件
          Set-Content -Path $yamlFile -Value $updatedYamlContent
        env:
          WINDOWS_APP_ID: ${{ secrets.WINDOWS_APP_ID }}
          WINDOWS_PUBLISHER_NAME: ${{ secrets.WINDOWS_PUBLISHER_NAME }}

      - uses: actions/upload-artifact@v4
        with:
          name: yq-artifact
          path: |
            windows\packaging\exe\make_config.yaml

  linux-envs:
    name: Get envs
    runs-on: ubuntu-22.04
    steps:
      - name: Configure .env
        run: |
          echo "$ENV_STG_BASE64" | base64 --decode > .stg.txt
          echo "$ENV_PROD_BASE64" | base64 --decode > .prod.txt
        env:
          ENV_STG_BASE64: ${{ secrets.ENV_STG_BASE64 }}
          ENV_PROD_BASE64: ${{ secrets.ENV_PROD_BASE64 }}

      - run: ls -la

      - uses: actions/upload-artifact@v4
        with:
          name: env-artifact
          include-hidden-files: true
          path: |
            *.txt
