name: Test Web With Rust

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

jobs:
  web-rust:
    name: Create web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for Linux
        run: |
          # https://github.com/getsentry/sentry-dart/issues/2504
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y curl libcurl4-openssl-dev git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.1'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configure .env
        run: echo "$ENV_KEY" | base64 --decode > .env
        env:
          ENV_KEY: ${{ secrets.ENV_STG_BASE64 }}

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Show rust version
        run: |
          cargo version
          rustc --version

      - name: Install flutter dependencies
        run: flutter pub get

      - name: Install rust dependencies
        run: cargo check
        working-directory: rust

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen

      - name: Build flutter rust bridge
        run: flutter_rust_bridge_codegen build-web --release

      - name: Build flutter
        run: flutter build web --dart-define-from-file=.env --target lib/main_free.dart

      - uses: actions/upload-artifact@v4
        with:
          name: web-artifact
          path: ./build/web

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f .env
